import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);
const STORAGE_KEY = "processlens-language";

const translations = {
  de: {
    locale: "de-DE",
    common: {
      upload: "Zum Upload",
      noDataTitle: "Keine Daten vorhanden",
      loadingData: "Daten werden geladen...",
      errorPrefix: "Fehler: ",
      cases: "Cases",
      count: "Anzahl",
      from: "Von",
      to: "Bis",
      apply: "Anwenden",
      reset: "Zurücksetzen",
      minimum: "Minimum",
      maximum: "Maximum",
      average: "Durchschnitt",
      median: "Median",
      secondsShort: "Sek.",
      minutesShort: "Min.",
      hoursShort: "Std.",
      days: "Tage",
    },
    nav: {
      upload: "Upload",
      overview: "Übersicht",
      bottleneckAnalysis: "Engpassanalyse",
      aiEvaluation: "KI-Auswertung",
      settings: "Einstellungen",
    },
    settings: {
      title: "Einstellungen",
      description: "Passen Sie die Anwendung an Ihre Arbeitsweise an.",
      languageTitle: "Sprache",
      languageDescription: "Wählen Sie die Sprache der Benutzeroberfläche.",
      german: "Deutsch",
      english: "Englisch",
      themeTitle: "Darstellung",
      themeDescription: "Wählen Sie zwischen hellem und dunklem Modus.",
      light: "Hell",
      dark: "Dunkel",
      defaultBadge: "Standard",
    },
    notFound: {
      message: "Seite nicht gefunden.",
      back: "Zurück zum Upload",
    },
    uploadPage: {
      description: "Laden Sie Ihren Event Log (CSV) hoch und ordnen Sie die Spalten zu.",
      dropzone: "CSV-Datei hierher ziehen oder klicken",
      chooseFile: "Datei auswählen",
      fileSelected: "Datei ausgewählt:",
      mapColumns: "Spalten zuordnen",
      mapDescription: "Ordnen Sie die Spalten Ihres Event Logs den entsprechenden Feldern zu.",
      activity: "Aktivität",
      timestamp: "Zeitstempel",
      uploading: "Wird hochgeladen...",
      startAnalysis: "Analyse starten",
      supportedFormat: "Unterstütztes Format: CSV mit Spalten für Case-ID, Aktivität und Zeitstempel.",
      uploadFailed: "Upload fehlgeschlagen",
    },
    overview: {
      title: "Übersicht",
      noDataMessage: "Um die Übersicht anzuzeigen, müssen Sie zuerst einen Event Log hochladen.",
      metricsFor: "Kennzahlen für",
      totalCases: "Anzahl Cases",
      totalEvents: "Anzahl Events",
      totalActivities: "Anzahl Aktivitäten",
      general: "Allgemein",
      throughputTime: "Durchlaufzeit",
      throughputDistribution: "Durchlaufzeitverteilung",
      throughputAxis: "Durchlaufzeit",
      casesAxis: "Anzahl Fälle",
      avgThroughput: "Ø Durchlaufzeit",
      chartInfo: "Die Grafik zeigt die Verteilung der Durchlaufzeiten aller Cases.",
    },
    bottleneck: {
      title: "Engpassanalyse",
      noDataMessage: "Um die Engpassanalyse anzuzeigen, müssen Sie zuerst einen Event Log hochladen.",
      largest: "Größte Engpässe",
      activityLevel: "Engpässe (Aktivitätsebene)",
      critical: "Kritisch",
      high: "Hoch",
      medium: "Mittel",
      low: "Gering",
      affected: "betroffen",
      totalInstances: "Bottleneck-Instanzen insgesamt",
      calculationTitle: "Wie wird ein Bottleneck berechnet?",
      calculationText: "Ein einzelner Durchlauf einer Aktivität (in einem konkreten Case) gilt als Bottleneck, wenn seine Dauer die Ausreißergrenze dieser Aktivität überschreitet (Q3 + 1,5 × Interquartilsabstand, Tukey-Methode). Dieses Maß berücksichtigt die natürliche Streuung jeder Aktivität, statt einen festen Anteil an Instanzen zu markieren.",
      assumptionTitle: "Annahme:",
      assumptionText: "Der Zeitstempel markiert im Event Log jeweils den Abschluss einer Aktivität. Die Dauer einer Aktivität ergibt sich daher aus der Zeit zwischen dem Abschluss der vorherigen und dem Abschluss der jeweiligen Aktivität im selben Case. Dadurch können auch Ruhezeiten (z.B. Nächte, Wochenenden oder sonstige Wartezeiten) in dieser Dauer enthalten sein.",
      activity: "Aktivität",
      avgDuration: "Ø Dauer",
      bottleneckCount: "Anzahl Bottlenecks",
      shareCases: "Anteil an Cases",
      bottleneckCountTitle: "Anzahl der Instanzen dieser Aktivität, deren Dauer über der Ausreißergrenze (Q3 + 1,5 × IQR) liegt",
      shareCasesTitle: "Anteil aller Cases im Event Log, in denen diese Aktivität mindestens einmal zum Bottleneck wurde",
      of: "von",
    },
    ai: {
      title: "KI-Auswertung",
      tabs: {
        processModel: "Prozessvarianten",
        deviation: "Soll-Ist-Vergleich",
        chat: "Chat",
      },
      warnings: {
        processModel: "Die Prozessgraphen werden mit KI generiert und können Fehler enthalten.",
        deviation: "Die Abweichungsanalyse wird mit KI generiert und kann Fehler enthalten.",
        chat: "Die Antworten im Chat werden mit KI generiert und können Fehler enthalten.",
      },
      noUpload: "Bitte zuerst eine Datei hochladen.",
      totalVariants: "Varianten insgesamt",
      topCoverage: "Abdeckung Top 10 (Anteil an Cases)",
      bpmnHeading: "BPMN 2.0 Prozessmodell - Variante",
      generations: "Generierungen",
      topVariants: "Top 10 Prozessvarianten",
      variant: "Variante",
      share: "Anteil",
      processModel: "Prozessmodell",
      shareTitle: "Anteil dieser Variante an allen Cases im Event Log",
      shown: "Angezeigt",
      show: "Anzeigen",
      generate: "Generieren",
      generating: "Generiert…",
      limitReached: "Limit erreicht",
      generatingModel: "Das Prozessmodell für Variante {idx} wird generiert…",
      generateTooltip: "Erzeugt ein BPMN 2.0 Prozessmodell für diese Variante",
      bpmnFailed: "BPMN-Rendering fehlgeschlagen: ",
      generationFailed: "BPMN-Generierung fehlgeschlagen.",
      noAnalysis: "Keine Analyse verfügbar.",
      summary: "Zusammenfassung",
      actualFlow: "Ist-Ablauf & Abweichungsanalyse",
      suggestions: [
        "Welche Aktivität ist der größte Engpass und warum?",
        "Wie lange dauert der Prozess im Durchschnitt bis zum Abschluss?",
        "Welche drei Verbesserungsmaßnahmen würdest du empfehlen?",
        "Gibt es Aktivitäten, die auffällig oft zu Engpässen führen?",
        "Welche Schlüsse lassen sich aus den häufigsten Prozessvarianten schließen?",
        "Wie stark unterscheiden sich die häufigsten Prozessvarianten voneinander?",
      ],
      chat: {
        noDataMessage: "Um Fragen zum Event Log zu stellen, müssen Sie zuerst einen Event Log hochladen.",
        messages: "Nachrichten",
        intro: "Stellen Sie eine offene Frage zum Event Log - die Antwort basiert auf den berechneten Kennzahlen und Engpässen.",
        examples: "Beispiele:",
        generating: "Antwort wird generiert...",
        limitUsed: "Chat-Limit erreicht",
        limitMessage: "Chat-Limit erreicht ({limit}/{limit} Nachrichten verwendet).",
        placeholder: "Frage zum Event Log stellen...",
        send: "Senden",
        answerFailed: "Antwort fehlgeschlagen.",
      },
      deviation: {
        noDataMessage: "Um die Abweichungsanalyse zu nutzen, müssen Sie zuerst einen Event Log hochladen.",
        description: "Laden Sie optional den Soll-Prozess als BPMN 2.0 Datei hoch. Die KI vergleicht ihn mit den {count} häufigsten tatsächlichen Prozessvarianten und beschreibt die Abweichungen.",
        dropzone: "Soll-Prozess (.bpmn) hierher ziehen oder klicken",
        noTargetTitle: "Kein Sollprozess hochgeladen",
        noTargetText: "es wird die häufigste Prozessvariante als Sollprozess verwendet.",
        running: "Analyse läuft...",
        start: "Abweichung analysieren",
        removeFile: "Datei entfernen",
        failed: "Analyse fehlgeschlagen.",
      },
    },
  },
  en: {
    locale: "en-US",
    common: {
      upload: "Go to upload",
      noDataTitle: "No data available",
      loadingData: "Loading data...",
      errorPrefix: "Error: ",
      cases: "cases",
      count: "Count",
      from: "From",
      to: "To",
      apply: "Apply",
      reset: "Reset",
      minimum: "Minimum",
      maximum: "Maximum",
      average: "Average",
      median: "Median",
      secondsShort: "sec.",
      minutesShort: "min.",
      hoursShort: "hrs.",
      days: "days",
    },
    nav: {
      upload: "Upload",
      overview: "Overview",
      bottleneckAnalysis: "Bottleneck Analysis",
      aiEvaluation: "AI Evaluation",
      settings: "Settings",
    },
    settings: {
      title: "Settings",
      description: "Customize the application for the way you work.",
      languageTitle: "Language",
      languageDescription: "Choose the language of the user interface.",
      german: "German",
      english: "English",
      themeTitle: "Appearance",
      themeDescription: "Choose between light and dark mode.",
      light: "Light",
      dark: "Dark",
      defaultBadge: "Default",
    },
    notFound: {
      message: "Page not found.",
      back: "Back to upload",
    },
    uploadPage: {
      description: "Upload your event log (CSV) and map the columns.",
      dropzone: "Drag a CSV file here or click",
      chooseFile: "Choose file",
      fileSelected: "File selected:",
      mapColumns: "Map columns",
      mapDescription: "Map the columns of your event log to the required fields.",
      activity: "Activity",
      timestamp: "Timestamp",
      uploading: "Uploading...",
      startAnalysis: "Start analysis",
      supportedFormat: "Supported format: CSV with columns for case ID, activity, and timestamp.",
      uploadFailed: "Upload failed",
    },
    overview: {
      title: "Overview",
      noDataMessage: "To view the overview, upload an event log first.",
      metricsFor: "Metrics for",
      totalCases: "Number of cases",
      totalEvents: "Number of events",
      totalActivities: "Number of activities",
      general: "General",
      throughputTime: "Throughput time",
      throughputDistribution: "Throughput time distribution",
      throughputAxis: "Throughput time",
      casesAxis: "Number of cases",
      avgThroughput: "Avg. throughput time",
      chartInfo: "The chart shows the distribution of throughput times across all cases.",
    },
    bottleneck: {
      title: "Bottleneck Analysis",
      noDataMessage: "To view the bottleneck analysis, upload an event log first.",
      largest: "Largest bottlenecks",
      activityLevel: "Bottlenecks by activity",
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
      affected: "affected",
      totalInstances: "bottleneck instances in total",
      calculationTitle: "How is a bottleneck calculated?",
      calculationText: "A single execution of an activity within a specific case counts as a bottleneck when its duration exceeds that activity's outlier threshold (Q3 + 1.5 × interquartile range, Tukey method). This measure accounts for the natural variation of each activity instead of marking a fixed share of instances.",
      assumptionTitle: "Assumption:",
      assumptionText: "The timestamp in the event log marks the completion of each activity. The duration of an activity is therefore derived from the time between completion of the previous activity and completion of the current activity in the same case. This means idle time, such as nights, weekends, or other waiting periods, can be included in the duration.",
      activity: "Activity",
      avgDuration: "Avg. duration",
      bottleneckCount: "Bottlenecks",
      shareCases: "Share of cases",
      bottleneckCountTitle: "Number of instances of this activity whose duration is above the outlier threshold (Q3 + 1.5 × IQR)",
      shareCasesTitle: "Share of all cases in the event log in which this activity became a bottleneck at least once",
      of: "of",
    },
    ai: {
      title: "AI Evaluation",
      tabs: {
        processModel: "Process Variants",
        deviation: "Target-Actual Comparison",
        chat: "Chat",
      },
      warnings: {
        processModel: "The process graphs are generated with AI and may contain errors.",
        deviation: "The deviation analysis is generated with AI and may contain errors.",
        chat: "Chat answers are generated with AI and may contain errors.",
      },
      noUpload: "Please upload a file first.",
      totalVariants: "Total variants",
      topCoverage: "Top 10 coverage (share of cases)",
      bpmnHeading: "BPMN 2.0 process model - variant",
      generations: "Generations",
      topVariants: "Top 10 process variants",
      variant: "Variant",
      share: "Share",
      processModel: "Process model",
      shareTitle: "Share of this variant across all cases in the event log",
      shown: "Shown",
      show: "Show",
      generate: "Generate",
      generating: "Generating…",
      limitReached: "Limit reached",
      generatingModel: "Generating process model for variant {idx}…",
      generateTooltip: "Generates a BPMN 2.0 process model for this variant",
      bpmnFailed: "BPMN rendering failed: ",
      generationFailed: "BPMN generation failed.",
      noAnalysis: "No analysis available.",
      summary: "Summary",
      actualFlow: "Actual flow & deviation analysis",
      suggestions: [
        "Which activity is the largest bottleneck and why?",
        "How long does the process take on average until completion?",
        "Which three improvement measures would you recommend?",
        "Are there activities that noticeably often lead to bottlenecks?",
        "What conclusions can be drawn from the most frequent process variants?",
        "How strongly do the most frequent process variants differ from each other?",
      ],
      chat: {
        noDataMessage: "To ask questions about the event log, upload an event log first.",
        messages: "Messages",
        intro: "Ask an open question about the event log - the answer is based on the calculated KPIs and bottlenecks.",
        examples: "Examples:",
        generating: "Generating answer...",
        limitUsed: "Chat limit reached",
        limitMessage: "Chat limit reached ({limit}/{limit} messages used).",
        placeholder: "Ask a question about the event log...",
        send: "Send",
        answerFailed: "Answer failed.",
      },
      deviation: {
        noDataMessage: "To use the deviation analysis, upload an event log first.",
        description: "Optionally upload the target process as a BPMN 2.0 file. The AI compares it with the {count} most frequent actual process variants and describes the deviations.",
        dropzone: "Drag the target process (.bpmn) here or click",
        noTargetTitle: "No target process uploaded",
        noTargetText: "the most frequent process variant will be used as the target process.",
        running: "Analysis running...",
        start: "Analyze deviation",
        removeFile: "Remove file",
        failed: "Analysis failed.",
      },
    },
  },
};

function getInitialLanguage() {
  if (typeof window === "undefined") return "de";

  const savedLanguage = window.localStorage.getItem(STORAGE_KEY);
  return savedLanguage === "en" ? "en" : "de";
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: translations[language],
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage muss innerhalb von LanguageProvider verwendet werden.");
  }

  return context;
}
